[playout]
# ./ means relative to the current directory; absolute paths are also valid
#folder = "./playout"
folder = "~/Playouts"

# when set, will use this time instead of "now" whenever this channel becomes active,
# which can be useful for troubleshooting
#virtual_start = "2026-04-12T19:04:30-05:00"

[ffmpeg]
# defaults to "ffmpeg" (must be in PATH)
#ffmpeg_path = "/usr/local/bin/ffmpeg"

# defaults to "ffprobe" (must be in PATH)
#ffprobe_path = "/usr/local/bin/ffprobe"

# filters listed here will be skipped when building the pipeline,
# which van be useful for working around hardware/driver bugs and/or limitations with specific filters
#disabled_filters = ["pad_vaapi", "pad_cuda"]

[normalization.audio]
# audio will be stream copied when format is not set (comment out the format line)
format = "aac"

bitrate_kbps = 192

buffer_kbps = 384

# integer number of channels, 2 means stereo, 6 means 5.1, etc.
channels = 2

[normalization.video]
# video will be stream copied when format is not set (comment out the format line)
# supported formats are `h264` and `hevc`
format = "hevc"

# when not stream copying,
bit_depth = 10

# video will be scaled and padded when width *and* height are both set
width = 1920

# video will be scaled and padded when width *and* height are both set
height = 1080

bitrate_kbps = 2_000

buffer_kbps = 4_000

# `cuda`, `qsv`, `vaapi`, `videotoolbox` and `vulkan` accels are minimally supported at this point
#accel = "cuda"

# algorithm used for tone mapping when transcoding HDR content
#tonemap_algorithm = "linear"

# when accel is `vaapi`, the path to the vaapi device is required
#vaapi_device = "/dev/dri/renderD128"

# when accel is `vaapi`, the vaapi driver name is required (iHD, i965, radeonsi)
#vaapi_driver = "i965"
