[server]
# ip address to bind to; `0.0.0.0` means all available addresses
bind_address = "0.0.0.0"
# HTTP port
port = 8409

[output]
# where to store transcoded content; this folder will be emptied by ersatztv
folder = "/tmp/hls"

[[channels]]
number = "1"
name = "ErsatzTV"
# ./ means relative to the current directory; absolute paths are also valid
# config = "./channels/1/channel.toml"
# config = "/config/channels/1/channel.toml"
config = "./channel.toml"
