name: Build Artifacts
on:
  workflow_call:
    inputs:
      release_tag:
        description: 'Release tag'
        required: true
        type: string
      release_version:
        description: 'Release version number (e.g. v0.1.0)'
        required: true
        type: string
      info_version:
        description: 'Informational version number (e.g. 0.1.0)'
        required: true
        type: string
    secrets:
      apple_developer_certificate_p12_base64:
        required: true
      apple_developer_certificate_password:
        required: true
      ac_username:
        required: true
      ac_password:
        required: true
      gh_token:
        required: true
      azure_client_id:
        required: true
      azure_tenant_id:
        required: true
      azure_subscription_id:
        required: true

permissions:
  id-token: write
  contents: write

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - run: rustup update stable
      - run: rustup show active-toolchain
      - run: rustup component add rustfmt clippy

      - run: cargo fmt --all -- --check
      - run: cargo clippy --locked --workspace --all-features --all-targets -- -D clippy::all

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: windows-x64
            rust_target: x86_64-pc-windows-gnu
            exe_ext: .exe
            archive_ext: .zip
          - os: ubuntu-latest
            target: linux-x64
            rust_target: x86_64-unknown-linux-gnu
            exe_ext: ""
            archive_ext: .tar.gz
          - os: ubuntu-latest
            target: linux-musl-x64
            rust_target: x86_64-unknown-linux-musl
            exe_ext: ""
            archive_ext: .tar.gz
          - os: ubuntu-latest
            target: linux-arm
            rust_target: armv7-unknown-linux-gnueabihf
            exe_ext: ""
            archive_ext: .tar.gz
          - os: ubuntu-24.04-arm
            target: linux-arm64
            rust_target: aarch64-unknown-linux-gnu
            exe_ext: ""
            archive_ext: .tar.gz
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - run: rustup update stable
      - run: rustup show active-toolchain

      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.rust_target }}

      - name: Build
        shell: bash
        run: |
          # Define some variables for things we need
          release_name="ersatztv-next-${{ inputs.release_version }}-${{ matrix.target }}"
          echo "RELEASE_NAME=${release_name}" >> $GITHUB_ENV

          # Build everything
          cargo build --release --all-features
          mkdir "$release_name"
          mv "target/${{ matrix.rust_target }}/release/ersatztv-playout-generator${{ matrix.exe_ext }}" "$release_name/"
          mv "target/${{ matrix.rust_target }}/release/ersatztv-channel${{ matrix.exe_ext }}" "$release_name/"
          mv "target/${{ matrix.rust_target }}/release/ersatztv${{ matrix.exe_ext }}" "$release_name/"

          if [ "${{ matrix.archive_ext }}" = ".zip" ]; then
            (cd "${release_name}" && 7z a "../${release_name}.zip" .)
          else
            tar czvf "${release_name}.tar.gz" "$release_name"
          fi

          # Delete output directory
          rm -r "$release_name"

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.target }}
          path: "*${{ matrix.archive_ext }}"

  publish:
    name: Publish
    needs: [lint, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: windows-x64
            archive_ext: .zip
          - target: linux-x64
            archive_ext: .tar.gz
          - target: linux-musl-x64
            archive_ext: .tar.gz
          - target: linux-arm
            archive_ext: .tar.gz
          - target: linux-arm64
            archive_ext: .tar.gz
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ matrix.target }}

      - name: Delete old release assets
        if: ${{ inputs.release_tag == 'develop' }}
        env:
          GH_TOKEN: ${{ secrets.gh_token }}
        run: |
          gh release view ${{ inputs.release_tag }} --json assets --jq '.assets[].name' --repo ${{ github.repository }} \
            | grep '${{ matrix.target }}${{ matrix.archive_ext }}' \
            | xargs -r -I{} gh release delete-asset ${{ inputs.release_tag }} {} --yes --repo ${{ github.repository }}

      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.gh_token }}
        run: gh release upload ${{ inputs.release_tag }} "*${{ matrix.archive_ext }}" --repo ${{ github.repository }}
